SELECT * FROM COUNTRY
WHERE COUNTRY LIKE 'A%a';

SELECT * FROM COUNTRY
WHERE COUNTRY LIKE '%_____n';

SELECT TITLE FROM FILM
WHERE TITLE ILIKE '%T%';

SELECT * FROM FILM
WHERE TITLE LIKE 'C%' AND LENGTH > 90 AND RENTAL_RATE = 2.99;
